'use strict';(function(){function E(d){let g=d.createConstantSource();g.offset.value=440;g.start();let c=new AudioWorkletNode(d,"pc-speaker-precision",{processorOptions:{updateHz:64}});var l=d.createGain();g.connect(l);l.connect(c);let p=d.createOscillator();p.type="sine";p.start();let q=d.createGain();q.gain.value=0;p.connect(q);q.connect(l.gain);let x=new AudioWorkletNode(d,"white-noise",{numberOfInputs:0}),u=d.createGain();u.gain.value=0;x.connect(u);u.connect(l.gain);let r=d.createConstantSource();
r.offset.value=0;r.start();r.connect(l.gain);l=d.createOscillator();l.frequency.value=0;l.type="square";c.connect(l.frequency);let v=d.createGain();l.connect(v);l.start();v.gain.value=0;return{outputNode:v,silenceAt(e){v.gain.setTargetAtTime(0,e,.01)},toneAt(e,t,a){g.offset.setTargetAtTime(t,e,.01);v.gain.setTargetAtTime(1,e,.01);"number"===typeof a&&v.gain.setTargetAtTime(0,e+a,.01)},vibratoAt(e,t,a,b){p.frequency.setValueAtTime(e,t);q.gain.setValueAtTime(Math.pow(2,a/12)-1,e);q.gain.setValueAtTime(0,
e+b)},noiseAt(e,t,a){u.gain.setValueAtTime(Math.pow(2,t/12)-1,e);u.gain.setValueAtTime(0,e+a)},pitchBend(e,t,a,{startDelay:b=0,endDelay:k=0,ease:h=m=>m}={}){if(0>a-b-k)throw Error("delays are longer than full duration");let m=Math.floor(64*(a-b-k));t=Math.pow(2,t/12)-1;let w=new Float32Array(m+1);for(let y=0;y<m;y++)w[y]=h(y/m)*t;w[m]=h(1)*t;r.offset.setValueAtTime(e,0);r.offset.setValueCurveAtTime(w,e+b,a-b-k);r.offset.setValueAtTime(e+a,0)}}}function A(d,g,c,l=120){var p,q,x;for(let e of g)switch(e.type){case "note":let t=
(null!==(p=e.semiquavers)&&void 0!==p?p:1)/(l/60*4);g=d;var u=g.toneAt,r=c,v=null!==(q=e.octave)&&void 0!==q?q:4;let a=B.indexOf(e.note);if(-1===a)throw Error("Invalid note");u.call(g,r,440*Math.pow(F,12*(v-4)+(a-G)),t-.01);c+=t;break;case "rest":g=(null!==(x=e.semiquavers)&&void 0!==x?x:1)/(l/60*4);c+=g;break;case "bpm":c=A(d,e.commands,c,e.bpm);break;case "hz":d.toneAt(c,e.hz,e.ms/1E3);c+=e.ms/1E3;break;case "off":c+=e.ms/1E3;break;case "vibrato":g=c;c=A(d,e.commands,g,l);d.vibratoAt(g,e.hz,e.semitones,
c-g);break;case "perturb":g=c,c=A(d,e.commands,g,l),d.noiseAt(g,e.semitones,c-g)}return c}function C(d,g=()=>{}){d=document.getElementById(d+"-template");let c=H(d.content);return()=>{let l=c.cloneNode(!0);g(l);return l}}function I(){return new Promise((d,g)=>{let c=document.createElement("input");c.type="file";c.onchange=l=>{var p;(null===(p=c.files)||void 0===p?0:p.length)?d(c.files[0]):d(null)};c.click()})}let B="C C# D D# E F F# G G# A A# B".split(" "),G=B.indexOf("A"),F=Math.pow(2,1/12),D=d=>
d.nodeType===Node.COMMENT_NODE||d.nodeType===Node.TEXT_NODE&&!/\S/.test(d.textContent||""),H=d=>{const g=d.firstElementChild;if(!g)return d;for(var c=g.previousSibling;c;c=c.previousSibling)if(!D(c))return d;for(c=g.nextSibling;c;c=c.nextSibling)if(!D(c))return d;return g};window.addEventListener("DOMContentLoaded",async function(){let d=C("block",a=>{const b=a.querySelector(".block")||a,k=b.querySelector(".block-type-selector");let h=k.value;b.classList.toggle(`mode-${h}`,!0);k.onchange=()=>{b.classList.toggle(`mode-${h}`,
!1);h=k.value;b.classList.toggle(`mode-${h}`,!0)};b.querySelector(".block-body").appendChild(g());b.querySelector(".delete-button").onclick=()=>{var m;null===(m=b.parentNode)||void 0===m?void 0:m.removeChild(b)}}),g=C("add-block-button",a=>{a.onclick=()=>{const b=d();a.parentNode.insertBefore(b,a);a.scrollIntoView({behavior:"smooth",block:"end",inline:"nearest"})}}),c=document.getElementById("blocks"),l=g();c.appendChild(l);let p=a=>{for(;l.previousElementSibling;)c.removeChild(l.previousElementSibling);
const b=(k,h)=>{var m,w,y;for(const n of h){h=d();var f=h.querySelector(".block")||h,z=f.querySelector(".block-type-selector");z.value=n.type;z.dispatchEvent(new Event("change"));switch(n.type){case "bpm":f.querySelector(".bpm > input").value=String(n.bpm);f=f.querySelector(".block-body > .add-block-button");b(f,n.commands);break;case "hz":f.querySelector(".raw-hz > input").value=String(n.hz);f.querySelector(".raw-duration > input").value=String(n.ms);break;case "note":f.querySelector(".tone-selector").value=
n.note;f.querySelector(".octave-selector").value=String(null!==(m=n.octave)&&void 0!==m?m:4);z=f.querySelector(".numerator");f=f.querySelector(".denominator");z.value=String(null!==(w=n.semiquavers)&&void 0!==w?w:1);f.value="16";break;case "off":f.querySelector(".raw-duration > input").value=String(n.ms);break;case "rest":z=f.querySelector(".numerator");f=f.querySelector(".denominator");z.value=String(null!==(y=n.semiquavers)&&void 0!==y?y:1);f.value="16";break;case "vibrato":f.querySelector(".semitones > input").value=
String(n.semitones);f.querySelector(".vibrato-hz > input").value=String(n.hz);f=f.querySelector(".block-body > .add-block-button");b(f,n.commands);break;case "perturb":f.querySelector(".semitones > input").value=String(n.semitones);f=f.querySelector(".block-body > .add-block-button");b(f,n.commands);break;case "bend":f.querySelector(".semitones > input").value=String(n.semitones),f=f.querySelector(".block-body > .add-block-button"),b(f,n.commands)}k.parentNode.insertBefore(h,k)}};b(l,a)},q=(a=c)=>
{const b=[];for(a=a.firstElementChild;a;a=a.nextElementSibling)if(a.classList.contains("block"))switch(a.querySelector(".block-type-selector").value){case "note":var k=a.querySelector(".tone-selector"),h=a.querySelector(".octave-selector"),m=a.querySelector(".numerator");const w=a.querySelector(".denominator");b.push({type:"note",note:k.value,octave:Number.parseFloat(h.value),semiquavers:Number.parseFloat(m.value)*Number.parseFloat(w.value)/16});break;case "rest":k=a.querySelector(".numerator");h=
a.querySelector(".denominator");b.push({type:"rest",semiquavers:Number.parseFloat(k.value)*Number.parseFloat(h.value)/16});break;case "bpm":k=a.querySelector(".bpm > input");h=q(a.querySelector(".block-body"));b.push({type:"bpm",bpm:Number.parseFloat(k.value),commands:h});break;case "hz":k=a.querySelector(".raw-hz > input");h=a.querySelector(".raw-duration > input");b.push({type:"hz",hz:Number.parseFloat(k.value),ms:Number.parseFloat(h.value)});break;case "off":k=a.querySelector(".raw-duration > input");
b.push({type:"off",ms:Number.parseFloat(k.value)});break;case "vibrato":k=a.querySelector(".semitones > input");h=a.querySelector(".vibrato-hz > input");m=q(a.querySelector(".block-body"));b.push({type:"vibrato",hz:Number.parseFloat(h.value),commands:m,semitones:Number.parseFloat(k.value)});break;case "perturb":k=a.querySelector(".semitones > input");h=q(a.querySelector(".block-body"));b.push({type:"perturb",commands:h,semitones:Number.parseFloat(k.value)});break;case "bend":k=a.querySelector(".semitones > input"),
h=q(a.querySelector(".block-body")),b.push({type:"bend",commands:h,semitones:Number.parseFloat(k.value)})}return b};document.getElementById("new-tune-button").onclick=()=>{p([])};document.getElementById("save-button").onclick=()=>{var a=new Blob([JSON.stringify({tune:q()})],{type:"application/json"});a=URL.createObjectURL(a);let b=document.createElement("a");b.download="tune.dostune.json";b.href=a;b.click()};document.getElementById("load-button").onclick=async()=>{let a=await I();if(a)try{p(JSON.parse(await a.text()).tune)}catch(b){alert(b)}};
let x=document.getElementById("example-selector");for(var u of document.querySelectorAll('script[type="application/json"]')){let a=u.getAttribute("id");if(!a)continue;let b=document.createElement("option");b.textContent=u.dataset.title||a;b.value=a;x.appendChild(b)}document.getElementById("load-example-button").onclick=()=>{let a=document.getElementById(x.value);a&&p(JSON.parse(a.text))};let r=new AudioContext;u=r.createGain();u.gain.value=.05;u.connect(r.destination);await r.audioWorklet.addModule("audio-worklet.js");
let v=E(r);v.outputNode.connect(u);let e=document.getElementById("play-button"),t=a=>new Promise(b=>void setTimeout(()=>b(),1E3*a));e.onclick=async()=>{e.disabled=!0;await r.resume();let a=A(v,q(),r.currentTime);await t(a-r.currentTime);e.disabled=!1}},{once:!0})})()
